name: 'Setup and install'
description: 'Common setup steps for Actions'

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v6
      with:
        run_install: false

    - uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: 'pnpm'

    - name: Install Turbo
      shell: bash
      run: pnpm add -g turbo

    - name: pnpm install
      shell: bash
      run: pnpm install
