packages:
  - packages/*
  - tooling/*

catalog:
  '@types/node': ^25.2.1
  eslint: ^9.39.2
  prettier: ^3.8.1
  typescript: ^5.9.3

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - lmdb
  - msgpackr-extract
  - unrs-resolver
