packages:
  - packages/*
  - tooling/*

catalog:
  '@commitlint/cli': 20.2.0
  '@commitlint/config-conventional': 20.2.0
  '@parcel/packager-ts': 2.16.3
  '@parcel/transformer-typescript-types': 2.16.3
  depcheck: 1.4.7
  glob: 13.0.0
  globals: 16.5.0
  husky: 9.1.7
  lint-staged: 16.2.7
  npm-check-updates: 19.2.0
  syncpack: 13.0.4
  turbo: 2.6.3
  typescript: 5.9.3

catalogs:
  eslint9:
    '@eslint/eslintrc': ^3.3.3
    '@eslint/js': ^9.39.2
    '@types/eslint': ^9.6.1
    '@types/eslint-plugin-jsx-a11y': 6.10.1
    '@types/eslint__js': ^9.14.0
    '@typescript-eslint/eslint-plugin': ^8.50.0
    '@typescript-eslint/parser': ^8.50.0
    eslint: ^9.39.2
    eslint-config-prettier: ^10.1.8
    eslint-import-resolver-alias: ^1.1.2
    eslint-import-resolver-typescript: ^4.4.4
    eslint-plugin-import: ^2.32.0
    eslint-plugin-jsx-a11y: ^6.10.2
    eslint-plugin-perfectionist: ^4.15.1
    eslint-plugin-prettier: ^5.5.4
    eslint-plugin-react: ^7.37.5
    eslint-plugin-react-compiler: 19.1.0-rc.2
    eslint-plugin-react-hooks: ^7.0.1
    eslint-plugin-react-you-might-not-need-an-effect: ^0.7.0
    eslint-plugin-regexp: ^2.10.0
    eslint-plugin-simple-import-sort: ^12.1.1
    eslint-plugin-storybook: ^10.1.10
    eslint-plugin-turbo: ^2.6.3
    eslint-plugin-unicorn: ^62.0.0
    eslint-plugin-unused-imports: ^4.3.0
    typescript-eslint: ^8.50.0
  next16:
    '@next/eslint-plugin-next': ^16.0.10
  node24:
    '@types/node': ^24.10.4
  prettier:
    '@ianvs/prettier-plugin-sort-imports': 4.7.0
    '@prettier/plugin-xml': 3.4.2
    prettier: 3.7.4
    prettier-plugin-packagejson: 2.5.20
    prettier-plugin-sort-json: 4.1.1
    prettier-plugin-tailwindcss: 0.7.2
